{% set python_min = "3.5" %}
{% set name = "gravis" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gravis-{{ version }}.tar.gz
  sha256: a36342602aa7da3bbd674c970439717926a8f7ca0678aa82cc5d756e8c2a529b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=40.0

test:
  imports:
    - gravis
  commands:
    - pip check
    - echo "Before ls"
    - ls -R
    - echo "After ls"
    - python -m pytest gravis/tests/
  source_files:
    - .
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://robert-haas.github.io/gravis-docs/
  summary: Interactive graph visualizations with Python and HTML/CSS/JS.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
