{% set python_min = "3.5" %}
{% set name = "gravis" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

https://github.com/robert-haas/gravis/archive/refs/tags/v{{ version }}.tar.gz
source:
  url: https://github.com/robert-haas/gravis/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8734066afd749fd85f9f173f92a1b501ae8e31723d1894c15f29fcec3eac5419

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=40.0

test:
  imports:
    - gravis
  commands:
    - pip check
    - echo "Before ls"
    - ls -R
    - echo "After ls"
    - python -m pytest tests/
  source_files:
    - .
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://robert-haas.github.io/gravis-docs/
  summary: Interactive graph visualizations with Python and HTML/CSS/JS.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
